// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  overviewSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        'overview/introduction',
        'overview/key-features',
        'overview/consensus',
        'overview/team-and-founder',
        'overview/community-and-adoption',
        'overview/future-developments',
        'overview/disclaimer'
      ],
    },
  ],
  learnSidebar: [
    {
      type: 'category',
      label: 'Basics',
      items: [
        'learn/basics/overview',
        'learn/basics/glossary',
        'learn/basics/tokenomics',
        'learn/basics/nodes',
        'learn/basics/spectrum',
        'learn/basics/architecture',
      ],
    },
    {
      type: 'category',
      label: 'Governance',
      items: [
        'learn/governance/governance',
        'learn/governance/quorum',
        'learn/governance/arbitrator',
        'learn/governance/steering-committee',
        'learn/governance/proposals',
        'learn/governance/decision-making',
        'learn/governance/dispute-resolution',
        'learn/governance/updates-changes',
      ],
    },
    {
      type: 'category',
      label: 'Mining',
      items: [
        'learn/mining/upow',
        'learn/mining/hw',
        'learn/mining/sw',
        'learn/mining/pool',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Concepts',
      items: [
        'learn/advanced-concepts/smart-contracts',
        'learn/advanced-concepts/ipo',
        'learn/advanced-concepts/dutch-auction',
        'learn/advanced-concepts/aigarth',
        'learn/advanced-concepts/oracles',
        'learn/advanced-concepts/environmental-impact',
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        'learn/user-guide/invest',
        'learn/user-guide/wallets',
        'learn/user-guide/exchanges',
        'learn/user-guide/qx',
      ],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      items: [
        'learn/ecosystem/use-cases',
        'learn/ecosystem/community-engagement',
        'learn/ecosystem/grants-program',
        'learn/ecosystem/hackathons',
        'learn/ecosystem/valis-project',
      ],
    },
    {
      type: 'category',
      label: 'Roadmap',
      items: [
        'learn/roadmap/milestones',
        'learn/roadmap/features',
        'learn/roadmap/releases',
        'learn/roadmap/project-x',
      ],
    },
    'learn/security',
  ],
 
  compSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'computors/challenges',
        'computors/prerequisites',
        'computors/installation',
        'computors/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Run a Computor',
      items: [
        'computors/bm',
        'computors/vm',
      ],
    },
    {
      type: 'category',
      label: 'Monitoring & Maintenance',
      items: [
        'computors/logging',
        'computors/commands',
        'computors/backup-restore',
        'computors/upgrading',
      ],
    },
  ],
  devSidebar: [
    'developers/intro',
    'developers/contribute',
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'developers/qubic-id',
        'developers/transactions',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Concepts',
      items: [
        'developers/oracles',
        'developers/qpi',
      ],
    },
    {
      type: 'category',
      label: 'Clients',
      items: [
        'api/rpc',
        'developers/rust-api'
      ],
    },
    {
      type: 'category',
      label: 'Community Bounties',
      items: [
        'developers/draft/logo',
      ],
    },
    {
      type: 'category',
      label: 'Implemented Proposals',
      items: [
        'developers/empty',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'developers/environment',
      ],
    },
    'developers/bug-bounty',
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'Core API',
      items: [
        'api/rpc',
        'api/transactions',
      ],
    },
  ],
};

module.exports = sidebars;